# python 3
FROM continuumio/anaconda3

MAINTAINER Alvin Ghouas
# set working directory
WORKDIR /usr/src/app

# clone from repo
#RUN git clone https://github.com/alvinalexander/e-mission-server.git .
COPY . /usr/src/app

# setup python environment.
RUN conda env update --name emission --file setup/environment36.yml
RUN /bin/bash -c "source activate emission; pip install six --upgrade"

RUN apt-get -y install nano

