name: docker-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
        - master
        - gis-based-mode-detection
  pull_request:
    branches:
        - master
        - gis-based-mode-detection
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: macos-latest
          PLATFORM: MacOSX-x86_64
        - os: ubuntu-latest
          PLATFORM: Linux-x86_64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: check my platform
      shell: bash -l {0}
      run: |
        uname -a
        uname -m

    - name: Setup docker and docker-compose (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        brew install docker docker-compose
        
        # Link the Docker Compose v2 plugin so it's understood by the docker CLI
        mkdir -p ~/.docker/cli-plugins
        ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
        
        colima start

    - name: try doing docker build
      shell: bash -l {0}
      run: |
        docker build -t emission-server .
