name: docker-build

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
        - master
        - gis-based-mode-detection
  pull_request:
    branches:
        - master
        - gis-based-mode-detection
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '5 4 * * 0'


jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
        - os: macos-latest
          PLATFORM: MacOSX-x86_64
        - os: ubuntu-latest
          PLATFORM: Linux-x86_64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: check my platform
      shell: bash -l {0}
      run: |
        uname -a
        uname -m

    - name: Setup docker, docker-compose, and colima (missing on MacOS)
      if: runner.os == 'macos'
      run: |
        HOMEBREW_NO_AUTO_UPDATE=1 brew install --cask docker
        sudo /Applications/Docker.app/Contents/MacOS/Docker --unattended --install-privileged-components
        open -a /Applications/Docker.app --args --unattended --accept-license
        echo "We are waiting for Docker to be up and running. It can take over 2 minutes..."
        while ! /Applications/Docker.app/Contents/Resources/bin/docker info &>/dev/null; do sleep 1; done

    - name: try doing docker build
      shell: bash -l {0}
      run: |
        docker build -t emission-server .